### ISSUE TITLE
Errore fine partita

### ISSUE THREAD

**Issue by martirius** [maicholD/Brisconline#2]
Browser: Firefox
S.O: MacOs Catalina
In una partita contro IA difficolta "difficile e anche stronzo" avendo fatto un punteggio di 73 mi viene scritto "Hai Perso" alla fine. 
E' errato perchè la partita è vinta

![Screen Shot 2020-08-24 at 09 39 10](https://user-images.githubusercontent.com/17033845/91017089-0bbaf380-e5ee-11ea-96e4-cf8789fba75c.png)

**Comment by maicholD** [comment]
risolto
